### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement faiss (from versions: none)

### ISSUE THREAD

**Issue by tianyang1027** [fierceX/Document_QA#2]
![image](https://user-images.githubusercontent.com/7963894/227140527-13571789-1933-4909-966a-3afad251b319.png)

**Comment by fierceX** [comment]
可能faiss不支持你的平台，我记得苹果m1芯片的机器无法安装，别的我没测试。其实，用faiss就是计算向量而已，如果不考虑复杂的应用，可以用sklearn代替

**Comment by tianyang1027** [comment]
我使用了faiss cpu版本安装上了，程序可以跑起来了
